"""Vendor current Wiki artwork using pinned Riot IDs/locales. Normal builds stay offline."""
import argparse
import concurrent.futures
import hashlib
import importlib.util
import json
from datetime import datetime, timezone
from pathlib import Path
import subprocess
import sys
import tempfile
import time
import urllib.request

sys.dont_write_bytecode = True
VERSION = '16.19.1'
ROOT = Path(__file__).resolve().parents[1]
CDN = 'https://ddragon.leagueoflegends.com/cdn/'
PNG = b'\x89PNG\r\n\x1a\n'


def load_parser(name, filename):
    spec = importlib.util.spec_from_file_location(name, ROOT / 'scripts' / filename)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


WIKI = load_parser('wiki_items', 'wiki-item-icons.py')
SPELLS = load_parser('wiki_spells', 'wiki-spell-icons.py')


def download(url):
    for attempt in range(3):
        try:
            request = urllib.request.Request(url, headers={'User-Agent': 'RiftReviewAssetSync/2.0'})
            with urllib.request.urlopen(request, timeout=30) as response:
                return response.read()
        except (OSError, TimeoutError):
            if attempt == 2:
                raise
            time.sleep(attempt + 1)


def metadata(kind, locale):
    return json.loads(download(f'{CDN}{VERSION}/data/{locale}/{kind}.json'))


def flattened_runes(styles):
    return [rune for style in styles for rune in [style] + [rune for slot in style['slots'] for rune in slot['runes']]]


def image_records(item_index, spell_index):
    records = []
    for kind, filename, parser, index in [('item', 'item', WIKI, item_index), ('spell', 'summoner', SPELLS, spell_index)]:
        english = metadata(filename, 'en_US')['data']
        vietnamese = metadata(filename, 'vi_VN')['data']
        for key, item in english.items():
            if kind == 'item' and not item.get('maps', {}).get('11'):
                continue
            identifier = str(key if kind == 'item' else item['key'])
            match = parser.lookup(index, identifier, item['name'])
            fallback = f"{CDN}{VERSION}/img/{kind}/{item['image']['full']}"
            records.append({'kind': kind, 'id': identifier, 'name': vietnamese[key]['name'], 'english': item['name'],
                            'url': match['url'] if match else fallback, 'pageUrl': parser.PAGE,
                            'provider': 'League of Legends Wiki' if match else 'Riot Data Dragon',
                            **({'wikiName': match['name']} if match else {'reason': 'No exact image in the Wiki catalog; current pinned Riot artwork used'})})
    return records


def auxiliary_metadata():
    localized = {rune['id']: rune['name'] for rune in flattened_runes(metadata('runesReforged', 'vi_VN'))}
    records = [{'kind': 'rune', 'id': str(rune['id']), 'name': localized[rune['id']], 'english': rune['name']}
               for rune in flattened_runes(metadata('runesReforged', 'en_US'))]
    shards = {5001: ('Máu theo cấp', 'Scaling Health'), 5002: ('Giáp (cũ)', 'Armor (legacy)'),
              5003: ('Kháng phép (cũ)', 'Magic Resist (legacy)'), 5005: ('Tốc độ đánh', 'Attack Speed'),
              5007: ('Điểm hồi kỹ năng', 'Ability Haste'), 5008: ('Sức mạnh thích ứng', 'Adaptive Force'),
              5010: ('Tốc độ di chuyển', 'Movement Speed'), 5011: ('Máu', 'Health'),
              5013: ('Kháng hiệu ứng và kháng làm chậm', 'Tenacity and Slow Resist')}
    records.extend({'kind': 'rune', 'id': str(identifier), 'name': names[0], 'english': names[1]} for identifier, names in shards.items())
    records.extend({'kind': 'rank', 'id': name.upper(), 'name': name, 'english': name}
                   for name in ['Iron', 'Bronze', 'Silver', 'Gold', 'Platinum', 'Emerald', 'Diamond', 'Master', 'Grandmaster', 'Challenger'])
    return records


def fetch_image(url):
    data = download(url)
    if not data.startswith(PNG) or data[12:16] != b'IHDR':
        raise ValueError('Not a PNG: ' + url)
    return data


def save_images(records):
    # Validate all downloads before replacing any files; existing spells are refreshed too.
    urls = list(dict.fromkeys(record['url'] for record in records))
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
        images = dict(zip(urls, pool.map(fetch_image, urls)))
    completed = []
    for record in records:
        data = images[record['url']]
        target = ROOT / 'public' / (record['kind'] + 's') / (record['id'] + '.png')
        target.parent.mkdir(exist_ok=True)
        target.write_bytes(data)
        completed.append({**record, 'sha256': hashlib.sha256(data).hexdigest()})
    return completed


def write_module(completed):
    maps = {kind: {a['id']: {'vi': a['name'], 'en': a['english']}
                   for a in completed if a['kind'] == kind}
            for kind in ['item', 'spell', 'rune', 'rank']}
    module = f'// Generated by scripts/sync-game-assets.py; Data Dragon {VERSION}.\n'
    module += '// Icon provenance: scripts/*-icon-sources.json; League Wiki with documented Riot fallbacks.\n'
    module += 'const names = {\n'
    for kind, entries in maps.items():
        module += '  ' + json.dumps(kind) + ': {\n'
        module += ''.join('    ' + json.dumps(identifier) + ': ' +
                          json.dumps(names, ensure_ascii=False) + ',\n'
                          for identifier, names in entries.items())
        module += '  },\n'
    module += '};\n'
    module += """
const assets = Object.freeze(Object.fromEntries(['vi', 'en'].map(locale => [
  locale, Object.freeze(Object.fromEntries(Object.entries(names).map(([kind, entries]) => [
    kind, Object.freeze(Object.fromEntries(Object.entries(entries).map(([id, translated]) => [
      id, Object.freeze({name: translated[locale], src: '/' + kind + 's/' + id + '.png'}),
    ]))),
  ]))),
])));

export function gameAsset(kind, id, language = 'vi') {
  const localized = assets[language === 'en' ? 'en' : 'vi'];
  if (!Object.hasOwn(localized, kind) || !['number', 'string'].includes(typeof id)) return null;
  const key = kind === 'rank' ? String(id).toUpperCase() : String(id);
  return Object.hasOwn(localized[kind], key) ? localized[kind][key] : null;
}
"""
    (ROOT / 'public/game-assets.js').write_text(module)


def sync_auxiliary(labels):
    subprocess.run([sys.executable, str(ROOT / 'scripts/sync-wiki-champions.py')], check=True)
    # Pass the newly fetched IDs/names: the generated browser module may be from an older patch.
    names = {record['id']: record['english'] for record in labels if record['kind'] == 'rune'}
    with tempfile.TemporaryDirectory(prefix='rift-rune-names-') as directory:
        source = Path(directory) / 'names.json'
        source.write_text(json.dumps(names), encoding='utf-8')
        subprocess.run([sys.executable, str(ROOT / 'scripts/sync-wiki-runes-ranks.py'),
                        '--rune-names', str(source)], check=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--items-spells-only', action='store_true', help='Refresh items/spells; keep separately synced champion/rune/rank images')
    args = parser.parse_args()
    item_index = WIKI.item_index(download(WIKI.PAGE).decode('utf-8'))
    spell_index = SPELLS.spell_index(download(SPELLS.PAGE).decode('utf-8'))
    records = image_records(item_index, spell_index)
    labels = auxiliary_metadata()
    if not args.items_spells_only:
        sync_auxiliary(labels)
    for record in labels:
        if not (ROOT / 'public' / (record['kind'] + 's') / (record['id'] + '.png')).exists():
            raise ValueError('Sync missing auxiliary icon before regenerating metadata: ' + record['id'])
    completed = save_images(records)
    write_module(completed + labels)
    for kind, group, page in [('item', 'items', WIKI.PAGE), ('spell', 'spells', SPELLS.PAGE)]:
        entries = {a['id']: {k: v for k, v in a.items() if k not in ['kind', 'id', 'name']} for a in completed if a['kind'] == kind}
        manifest = {'metadataVersion': VERSION, 'page': page, 'retrievedAt': datetime.now(timezone.utc).isoformat(), group: entries}
        (ROOT / 'scripts' / f'{kind}-icon-sources.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
        print(group + ':', {provider: sum(a['provider'] == provider for a in entries.values())
                            for provider in ['League of Legends Wiki', 'Riot Data Dragon']})


if __name__ == '__main__':
    main()
